//! Calibrated CLR verdicts — the first `sigmoid_calibration` consumer
//! (riir-ai Issue 964 C1; substrate: katgpt-rs Issue 810, Bench 807).
//!
//! [`SigmoidProjectionVerifier`](crate::clr::verifier::SigmoidProjectionVerifier)'s
//! verdicts are **bounded** in `(0, 1)` — that much is true by construction.
//! Whether they are **calibrated** (a verdict of 0.8 meaning "80% of such
//! claims come true") is a property of the direction vectors and the claim
//! embedding scale, not of the sigmoid, and it drifts as either side moves
//! (every `DirectionVectorSource::version` bump re-scales the dot products).
//! Bench 284's G2 gate measured ECE 0.0087 on a fixture whose ground truth
//! was generated by the *same* sigmoid — that proves boundedness again, not
//! robustness to drift.
//!
//! This module wraps any [`ClaimVerifier`] with a
//! [`SigmoidGateCalibrator`](katgpt_core::sigmoid_calibration::SigmoidGateCalibrator):
//!
//! 1. **observe** — record `(raw sigmoid verdict, binary outcome)` pairs
//!    wherever ground truth is known (the Bench 284 G2 harness points are the
//!    canonical example: verdict + Bernoulli label).
//! 2. **refit** — off-hot-path deterministic 2-param Platt refit.
//! 3. **apply** — in front of the reliability gate: the raw verdict feeds the
//!    calibrator, the calibrated probability feeds `r_k = (mean_m v_k,m)^M`.
//!
//! # Contract
//!
//! - **Cold start is bit-identical.** At identity parameters `apply` returns
//!   the input unchanged (the substrate's exact-value fast path), so wrapping
//!   a verifier before any evidence exists changes nothing — same verdicts,
//!   same winner, same bytes.
//! - **Monotone, never inverting.** The fitted scale is `w = 1/T > 0`, so
//!   `apply` is strictly monotone: pairwise verdict order is preserved and a
//!   ranking over raw verdicts survives calibration. Aggregate reliability
//!   ordering can still move — that is the correction doing its job.
//! - **Latent-domain rules.** Calibration is a LOCAL monotone transform.
//!   Calibrated verdicts never cross a sync boundary, never feed
//!   anti-cheat/replay paths, and are never written where a raw scalar is
//!   expected (the user's `AGENTS.md` latent-vs-rules).

use crate::clr::traits::ClaimVerifier;
use crate::clr::types::Verdict;
use katgpt_core::sigmoid_calibration::SigmoidGateCalibrator;

/// A [`ClaimVerifier`] wrapper applying a Platt-calibrated monotone
/// transform in front of the CLR reliability gate.
///
/// Generic over the inner verifier `V` — typically
/// [`SigmoidProjectionVerifier`](crate::clr::verifier::SigmoidProjectionVerifier),
/// but any implementor composes. The calibrator is owned (single consumer);
/// snapshot it via [`Self::params`] + [`Self::commitment`] for freeze/thaw.
///
/// # Example
///
/// ```
/// use katgpt_claim::clr::SigmoidProjectionVerifier;
/// use katgpt_claim::clr::ClaimVerifier;
/// use katgpt_claim::clr::calibration::CalibratedVerifier;
/// # use katgpt_claim::clr::DirectionVectorSource;
/// # struct OneDir { v: Vec<f32> }
/// # impl DirectionVectorSource for OneDir {
/// #     fn direction(&self, _i: usize) -> &[f32] { &self.v }
/// #     fn blake3(&self) -> [u8; 32] { *blake3::hash(bytemuck::cast_slice(&self.v)).as_bytes() }
/// #     fn version(&self) -> u64 { 1 }
/// # }
/// let dirs = OneDir { v: vec![1.0, 0.0] };
/// let inner = SigmoidProjectionVerifier::new(&dirs, 2);
/// let mut calibrated = CalibratedVerifier::new(inner, 1024, 128);
///
/// // Where ground truth is known: record (raw verdict, outcome). The raw
/// // verdict comes from the INNER verifier (the calibrator maps raw → cal).
/// let claim = katgpt_claim::clr::Claim::<()> {
///     embedding: vec![0.5, 0.0],
///     payload: (),
/// };
/// let raw = calibrated.inner().verify(&claim, 0);
/// calibrated.observe(raw, true);
///
/// // Off-hot-path refit; identity until min_obs evidence accumulates.
/// calibrated.refit();
///
/// // The vote path sees calibrated verdicts; cold start is bit-identical.
/// let v = calibrated.verify(&claim, 0);
/// assert!((0.0..1.0).contains(&v));
/// ```
pub struct CalibratedVerifier<V> {
    inner: V,
    calibrator: SigmoidGateCalibrator,
}

impl<V> CalibratedVerifier<V> {
    /// Wrap `inner` with an identity-calibrated gate.
    ///
    /// `capacity` / `min_obs` are the [`SigmoidGateCalibrator`] evidence
    /// window size and occupancy floor — see its docs. Until `min_obs`
    /// pairs are observed and [`Self::refit`] moves the parameters, every
    /// verdict passes through **bit-identically**.
    pub fn new(inner: V, capacity: usize, min_obs: usize) -> Self {
        Self {
            inner,
            calibrator: SigmoidGateCalibrator::new(capacity, min_obs),
        }
    }

    /// Record one `(raw sigmoid verdict, binary outcome)` pair.
    ///
    /// `raw_verdict` is the value the INNER verifier produced — not a
    /// previously calibrated output. The Platt map is fitted from raw
    /// sigmoid outputs; feeding it its own output compounds the transform.
    /// Zero-alloc, O(1).
    #[inline]
    pub fn observe(&mut self, raw_verdict: f32, outcome: bool) {
        self.calibrator.observe(raw_verdict, outcome);
    }

    /// Off-hot-path refit of the calibration parameters over the evidence
    /// window. Returns `true` when the parameters moved. Below `min_obs`
    /// occupancy this is a no-op and the gate stays bit-identical.
    pub fn refit(&mut self) -> bool {
        self.calibrator.refit()
    }

    /// Current parameters as `(T, b)` in `p_cal = sigmoid((logit(p) − b)/T)`.
    /// `T > 0` always (the monotonicity guard).
    pub fn params(&self) -> (f32, f32) {
        self.calibrator.params()
    }

    /// BLAKE3 commitment over the calibrator's versioned canonical bytes —
    /// freeze/thaw evidence for "which calibration produced these verdicts".
    pub fn commitment(&self) -> [u8; 32] {
        self.calibrator.commitment()
    }

    /// Borrow the inner (uncalibrated) verifier — the source of the raw
    /// verdicts [`Self::observe`] expects.
    pub fn inner(&self) -> &V {
        &self.inner
    }

    /// Mutably borrow the inner verifier.
    pub fn inner_mut(&mut self) -> &mut V {
        &mut self.inner
    }

    /// Unwrap into the inner verifier (drops the evidence window).
    pub fn into_inner(self) -> V {
        self.inner
    }
}

impl<T, V: ClaimVerifier<T>> ClaimVerifier<T> for CalibratedVerifier<V> {
    /// Calibrated verdict: the inner verifier's raw sigmoid output passes
    /// through the calibrator BEFORE the reliability gate consumes it.
    /// One logit + one fma + one sigmoid on the fitted path; the identity
    /// fast path returns the raw verdict bit-identically.
    #[inline(always)]
    fn verify_embedding(&self, embedding: &[f32], direction_idx: usize) -> Verdict {
        self.calibrator
            .apply(self.inner.verify_embedding(embedding, direction_idx))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::clr::traits::DirectionVectorSource;
    use crate::clr::verifier::SigmoidProjectionVerifier;

    /// Minimal single-direction source (the verifier.rs fixture shape).
    struct OneDir {
        v: Vec<f32>,
    }

    impl DirectionVectorSource for OneDir {
        fn direction(&self, _i: usize) -> &[f32] {
            &self.v
        }
        fn blake3(&self) -> [u8; 32] {
            *blake3::hash(bytemuck::cast_slice(&self.v)).as_bytes()
        }
        fn version(&self) -> u64 {
            1
        }
    }

    fn dirs() -> OneDir {
        // Unit-norm direction so dot(emb, dir) = emb[0].
        OneDir {
            v: vec![1.0, 0.0, 0.0, 0.0],
        }
    }

    /// Cold start: every verdict passes through bit-identically — the exact
    /// value, not a float twin of it.
    #[test]
    fn cold_start_verdicts_are_bit_identical() {
        let d = dirs();
        let inner = SigmoidProjectionVerifier::new(&d, 4);
        let calibrated = CalibratedVerifier::new(inner, 64, 8);
        for i in 0..64u32 {
            let x = (i as f32 / 16.0) - 2.0; // dots span [-2, 2)
            let claim = crate::clr::types::Claim::<()> {
                embedding: vec![x, 0.5, -0.25, 0.125],
                payload: (),
            };
            let raw = calibrated.inner().verify(&claim, 0);
            let cal = calibrated.verify(&claim, 0);
            assert_eq!(raw.to_bits(), cal.to_bits(), "x = {x}");
        }
    }

    /// After a REAL refit the transform is strictly monotone: pairwise
    /// verdict order survives (ties allowed under float rounding, inversions
    /// never).
    #[test]
    fn refit_never_inverts_verdict_order() {
        let d = dirs();
        let inner = SigmoidProjectionVerifier::new(&d, 4);
        let mut calibrated = CalibratedVerifier::new(inner, 256, 32);
        // Miscalibrated evidence: high dots systematically wrong-side.
        for i in 0..256 {
            let x = (i as f32 / 64.0) - 2.0;
            let raw = 1.0 / (1.0 + (-x).exp());
            calibrated.observe(raw, x < 0.0);
        }
        assert!(calibrated.refit());
        let (t, _b) = calibrated.params();
        assert!(t > 0.0, "T must stay positive");

        let mut prev_raw = f32::NEG_INFINITY;
        let mut prev_cal = f32::NEG_INFINITY;
        for i in 0..512 {
            let x = (i as f32 / 128.0) - 2.0;
            let claim = crate::clr::types::Claim::<()> {
                embedding: vec![x, 0.0, 0.0, 0.0],
                payload: (),
            };
            let raw = calibrated.inner().verify(&claim, 0);
            let cal = calibrated.verify(&claim, 0);
            assert!(raw >= prev_raw && cal >= prev_cal, "order inverted at x = {x}");
            prev_raw = raw;
            prev_cal = cal;
        }
    }

    /// `verify` (the Claim<T> path) delegates through the calibrated
    /// `verify_embedding`.
    #[test]
    fn claim_path_delegates_through_calibration() {
        let d = dirs();
        let inner = SigmoidProjectionVerifier::new(&d, 4);
        let mut calibrated = CalibratedVerifier::new(inner, 64, 8);
        let claim = crate::clr::types::Claim::<()> {
            embedding: vec![1.5, 0.0, 0.0, 0.0],
            payload: (),
        };
        // Cold start: identical to the raw verifier.
        let raw = calibrated.inner().verify(&claim, 0);
        let cal = calibrated.verify(&claim, 0);
        assert_eq!(raw.to_bits(), cal.to_bits());

        // After a miscalibrating refit the value moves but stays in (0, 1).
        for i in 0..64 {
            let p = 0.02 + 0.96 * i as f32 / 63.0;
            calibrated.observe(p, p < 0.4);
        }
        assert!(calibrated.refit());
        let moved = calibrated.verify(&claim, 0);
        assert!((0.0..1.0).contains(&moved));
        assert_ne!(moved.to_bits(), raw.to_bits());
    }

    /// Deterministic refit + commitment: same evidence, same parameters,
    /// same BLAKE3 (the freeze/thaw evidence contract).
    #[test]
    fn refit_and_commitment_are_deterministic() {
        let evidence = |i: u32| (0.02 + 0.96 * i as f32 / 511.0, i % 7 != 3);
        let fit = || {
            let d = dirs();
            let inner = SigmoidProjectionVerifier::new(&d, 4);
            let mut c = CalibratedVerifier::new(inner, 512, 64);
            for i in 0..512 {
                let (p, y) = evidence(i);
                c.observe(p, y);
            }
            assert!(c.refit());
            (c.params(), c.commitment())
        };
        assert_eq!(fit(), fit());
    }
}
